//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNominas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empprin
    {
        public string CLAVE { get; set; }
        public string NOMBREN { get; set; }
        public string NOMBREP { get; set; }
        public string NOMBREM { get; set; }
        public Nullable<System.DateTime> INGRESO { get; set; }
        public Nullable<System.DateTime> PLANTA { get; set; }
        public string FOTO { get; set; }
        public string PE { get; set; }
        public string RFC { get; set; }
        public string TIPO_NOM { get; set; }
        public string TIPO_PAGO { get; set; }
        public string TURNO { get; set; }
        public string CTA_TARJETA { get; set; }
        public Nullable<bool> PTU { get; set; }
        public Nullable<bool> CUOTA_SINDICAL { get; set; }
        public Nullable<decimal> VALOR_MINUTO { get; set; }
        public string AFILIACION { get; set; }
        public string BANCO_SAR { get; set; }
        public string SUCURSAL { get; set; }
        public string CTA_CHEQUES { get; set; }
        public string CONTROL_INTERNO { get; set; }
        public Nullable<decimal> APORTACION_SAR { get; set; }
        public Nullable<decimal> APORTACION_INFONAVIT { get; set; }
        public string CREDITO_INFONAVIT { get; set; }
        public Nullable<System.DateTime> INICIO_DESCUENTO_INF { get; set; }
        public string TIPO_DESCUENTO { get; set; }
        public Nullable<decimal> VALOR_DESCUENTO { get; set; }
        public string CURP { get; set; }
        public Nullable<short> JORNADA_REDUCIDA { get; set; }
        public Nullable<short> SEMANA_REDUCIDA { get; set; }
        public string CALENDARIO { get; set; }
        public Nullable<decimal> COSTO_COMEDOR { get; set; }
        public Nullable<bool> BLOQUEAR_COMEDOR { get; set; }
        public Nullable<System.DateTime> FECHA_CAPTURA { get; set; }
        public Nullable<decimal> SDO_VAC_INI { get; set; }
        public Nullable<decimal> SDO_VAC_INI_PRIMA { get; set; }
        public string TURNOINT { get; set; }
        public string TURNO_ROTATIVO { get; set; }
        public Nullable<bool> NO_ACTIVO { get; set; }
        public Nullable<System.DateTime> FIN_DESCUENTO_INF { get; set; }
        public string BANCOSAT { get; set; }
        public string REGIMENCONTSAT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ENVIAR_CFDI { get; set; }
        public string RFCOUT { get; set; }
        public string TIPO_CONTRATO { get; set; }
        public string TIPO_JORNADA { get; set; }
        public string REGIMENFISCAL { get; set; }
    }
}
